# Run tests and, if successful, build and publish the PyPI library
# cf. https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Publish

on:
  push:
    branches: [ "main", "dev" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:


permissions:
  contents: read


jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12", "3.13" ]   # Run tests on both 3.12 and 3.13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm install --dev --global --no-lock --no-self --project .

      - name: Lint with ruff
        run: |
          # stop the build if linting fails 
          ruff check .

      - name: Test with pytest
        run: |
          pytest


  check_current_branch:
    # cf. https://stackoverflow.com/a/72959712/5220723
    runs-on: ubuntu-latest
    needs: run_tests
    outputs:
      branch: ${{ steps.check_branch.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_branch
        # 1. Get the list of branches ref where this tag exists
        # 2. Remove 'origin/' from that result
        # 3. Put that string in output
        # => We can now use function 'contains(list, item)''
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For pull requests, set 'raw' to be the triggering ref (branch)
            raw="${{ github.ref }}"
          else
            # Otherwise, use the git command to retrieve related branches
            raw=$(git branch -r --contains ${{ github.ref }})
          fi
          branch="$(echo ${raw//origin\//} | tr -d '\n')"
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "Branches where this tag exists : $branch."     
      
      - name: Check tag for SemVer
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          # This regex matches: 1.2.3, v1.2.3, 1.2.3-rc1, v1.2.3-beta.1, etc.
          if [[ ! "$TAG" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.]+)?$ ]]; then
            echo "::error ::Tag '$TAG' is not a valid SemVer. Skipping build."
            exit 1
          fi


  publish_pypi:
    name: Build and Publish Python Package to PyPI/TestPyPI
    if: |
      (
        (
          startsWith(github.ref, 'refs/tags/')
          && contains(needs.check_current_branch.outputs.branch, 'main')
        )
        || github.event_name == 'workflow_dispatch'
      )
    needs: check_current_branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM and build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm install --prod --no-lock --no-self --project .

      - name: Build package with PDM
        run: |
          pdm build

      - name: Publish to PyPI on main tag, or TestPyPI on manual workflow dispatch
        env:
          TWINE_USERNAME: __token__
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          pip install twine
          twine check dist/*
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
            if [ -z "$TEST_PYPI_API_TOKEN" ]; then
              echo "::error ::TEST_PYPI_API_TOKEN is not set!"
              exit 1
            fi
            echo "Uploading to TestPyPI..."
            twine upload --non-interactive --verbose --repository-url https://test.pypi.org/legacy/ -u __token__ -p "$TEST_PYPI_API_TOKEN" dist/*
          else
            if [ -z "$PYPI_API_TOKEN" ]; then
              echo "::error ::PYPI_API_TOKEN is not set!"
              exit 1
            fi
            echo "Uploading to PyPI..."
            twine upload --non-interactive -u __token__ -p "$PYPI_API_TOKEN" dist/*
          fi